apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-api-ingress
  labels:
    app.kubernetes.io/name: kubewebapp
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: webapp
    app.kubernetes.io/managed-by: helm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/hsts: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webapp-api-service
            port:
              number: {{ .Values.service.port }}